[debug] [2024-02-20T19:04:46.016Z] ----------------------------------------------------------------------
[debug] [2024-02-20T19:04:46.019Z] Command:       /home/kennedy/.nvm/versions/node/v18.18.0/bin/node /home/kennedy/.nvm/versions/node/v18.18.0/bin/firebase init
[debug] [2024-02-20T19:04:46.019Z] CLI Version:   13.0.1
[debug] [2024-02-20T19:04:46.020Z] Platform:      linux
[debug] [2024-02-20T19:04:46.020Z] Node Version:  v18.18.0
[debug] [2024-02-20T19:04:46.040Z] Time:          Tue Feb 20 2024 22:04:46 GMT+0300 (East Africa Time)
[debug] [2024-02-20T19:04:46.041Z] ----------------------------------------------------------------------
[debug] 
[debug] [2024-02-20T19:04:46.044Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[debug] [2024-02-20T19:04:46.172Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2024-02-20T19:04:46.172Z] > authorizing via signed-in user (kennedynjogu8@gmail.com)
[info] 
     ######## #### ########  ######## ########     ###     ######  ########
     ##        ##  ##     ## ##       ##     ##  ##   ##  ##       ##
     ######    ##  ########  ######   ########  #########  ######  ######
     ##        ##  ##    ##  ##       ##     ## ##     ##       ## ##
     ##       #### ##     ## ######## ########  ##     ##  ######  ########

You're about to initialize a Firebase project in this directory:

  /home/kennedy/Documents/ngrx/beta-app

Before we get started, keep in mind:

  * You are initializing within an existing Firebase project directory

[debug] [2024-02-20T19:04:50.992Z] <<< [apiv2][status] GET https://firebase-public.firebaseio.com/cli.json 200
[debug] [2024-02-20T19:04:50.993Z] <<< [apiv2][body] GET https://firebase-public.firebaseio.com/cli.json {"cloudBuildErrorAfter":1594252800000,"cloudBuildWarnAfter":1590019200000,"defaultNode10After":1594252800000,"minVersion":"3.0.5","node8DeploysDisabledAfter":1613390400000,"node8RuntimeDisabledAfter":1615809600000,"node8WarnAfter":1600128000000}
[debug] [2024-02-20T19:05:05.179Z] Error: Timed out.
    at Timeout._onTimeout (/home/kennedy/.nvm/versions/node/v18.18.0/lib/node_modules/firebase-tools/lib/utils.js:258:49)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[error] 
[error] Error: An unexpected error has occurred.
